src/components/Tabs/Tabs.tsx

Due to RTL implementation tabs were scrolling into view. This pr reverts this functionality

fix(tabs component): revert previous functionality of scrolling in tabs

---

src/components/Modal/Modal.stories.tsx
src/components/Modal/Modal.test.tsx
src/components/Modal/Modal.tsx
src/components/Modal/__snapshots__/Modal.test.tsx.snap

When onClose function is undefined, then do not render the close button
This PR affects the Modal component
A new story added for Modal with no close button
A new test written for Modal with no close button

fix(modal.tsx): do not render close button when onClose is undefined

---

src/components/Table/Table.stories.tsx
src/components/Table/Table.tsx
src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
src/components/Table/components/Body.tsx
src/components/Table/components/Header.tsx
src/components/Table/types.ts

BREAKING CHANGE: The callback handleRowClick has changed to onRowClick
- Added a callback (onRowSelect) to return the selected rows.
- Changed a callback function name from handleRowClick to onRowClick returning the clicked row item data.

feat(table component): add callbacks for the table row selections

---

src/components/Pagination/Pagination.stories.tsx
src/components/Pagination/Pagination.tsx
src/components/Table/Table.stories.tsx
src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
src/components/Table/components/Body.tsx
src/components/Table/components/Cell.tsx
src/components/Table/styles.ts
src/components/Table/types.ts

In a column with maxWidth set, display a tooltip with it's content when there is overflown text.
- Add maxWidth prop in Column type
- Show tooltip for overflown content
In order to work the described behaviour must:
- Apply max width in the desired column column
- Have to be add, in the parent of the element that contains the render text, a "has-overflow" class

fix(table): display tooltip in overflow columns

---

src/components/Table/Table.stories.tsx
src/components/Table/components/Body.tsx
src/components/Table/components/Cell.tsx

Resizing window didn't trigger tooltip when needed.
Every time the window resizes now we check again for overflow.

fix: resizing window apply tooltip

---

src/components/Table/Table.stories.tsx
src/components/Table/Table.tsx
src/components/Table/components/Header.tsx
src/components/Table/types.ts

We want to only use 2 states when sorting a column in tables.
States are now ascending and descending only.
The no sorting state is removed.

fix: two states sorting in tables

---

src/components/Tabs/Tabs.stories.tsx
src/components/Tabs/Tabs.test.tsx
src/components/Tabs/Tabs.tsx
src/components/Tabs/TabsNavItem.tsx

Improve the way we handle tab props as it previously could lead to unexpected behavior
BREAKING CHANGE: You need to refactor your <Tabs> component with suitable props. No more passing content as children.

Refactor Tabs

---

src/components/Chip/__snapshots__/Chip.test.tsx.snap
src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/styles.ts

The tooltip arrow needs to be centered in tippy component.
Adding tippy prop(interactive) to keep tooltip visible when hovering.
Adding some margins to make arrow centered for every tooltip placement.

fix: centering tooltip arrow

---

src/components/Button/Button.tsx
src/components/Button/styles.ts

Bug cause due to having rules with the same name
Change the name of link button class
---
- https://app.asana.com/0/0/1205820631366084

fix: rename link button class

---

src/components/FormElements/Select/Select.stories.tsx
src/components/FormElements/Select/Select.tsx
src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
src/components/FormElements/Select/styles.ts
src/components/FormElements/Select/types.ts

This PR implements the addition of tooltipContent to Select component
Show info icon next to Select component's label, when the `tooltipContent` attribute is provided

chore(select): add tooltip content to Select component

---

src/components/FormElements/Select/Select.stories.tsx
src/components/FormElements/Select/Select.tsx
src/components/FormElements/Select/types.ts

The Select component in Gnosis should be allowed to pass as a validation hook as a prop to allow specific new input values.
Passing a validation hook that returns boolean type and using it as prop in CreatableSelect.

fix: validating new input values on select component

---

src/components/FormElements/Select/Select.stories.tsx
src/components/FormElements/Select/Select.tsx
src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
src/components/FormElements/Select/styles.ts
src/components/FormElements/Select/types.ts

When adding a new valid option we need also to check for duplicates. Also having an option selected should display a message according to that.
- Adding a check if a value is valid and not duplicate
- Adding a helper to change the default no options message

fix: Select component duplicate values and no options message

---

src/components/Chip/__snapshots__/Chip.test.tsx.snap
src/components/Tooltip/Tooltip.tsx

Change the parentAriaRole to be "tooltip" as default.

chore(tooltip): change default value of parentAriaRole

---

src/components/Tooltip/Tooltip.tsx

Since the props of the tooltip are being spread on the Tippy component. In some cases, we need to pass custom aria roles and properties to the tooltip tag (not tippy). An extra prop that accepts an object for custom props has been added that is spread to the Tag component.

chore(tooltip): add parent props for custom props

---

src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap

Task: [URL](https://app.asana.com/0/1206939712119890/1208434092887351/f)
fix miss aligned icons on dropdown items due to tooltip placement on content instead of liElement as
a whole

fix(dropdown): fixing miss aligned icons on dropdown items due to tooltip

---

src/components/StatusTag/StatusTag.stories.tsx
src/components/StatusTag/StatusTag.test.tsx
src/components/StatusTag/StatusTag.tsx
src/components/StatusTag/styles.ts

Change all enums to union types since props needs the actual enum key to associate the values.

chore(status tag): refactor all enums to union types

---

src/components/Breadcrumbs/Breadcrumbs.tsx

This PR implements a fix on Breadcrumbs arrow icons when document direction is RTL

fix(breadcrumbs): fix arrows on RTL dirction

---

src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
src/components/FormElements/Select/styles.ts

fixes the ratio of label:hint inside the option of the Select

fix(select): adjust the ratio of label:hint to be 1:1

---

src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/Checkbox.test.tsx.snap
src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/CheckboxGroup.test.tsx.snap
src/components/FormElements/CheckboxGroup/styles.ts

Add pointer events:none to dash span in order for the whole checkbox to be clickable
---
- https://app.asana.com/0/0/1206426342317349

chore(checkbox.tsx): add pointer events none to dash span

---

src/components/Modal/Modal.tsx

This PR introduces `onAfterOpen` prop to `Modal`.
We wanted to focus on a textfield as soon as the modal opens. That's how the need for that came up.
https://github.com/user-attachments/assets/b84a305b-a4cd-4193-9283-808140b7f213

chore(modal.tsx): introduce onAfterOpen prop to Modal

---

src/components/FormElements/ToggleSwitch/ToggleSwitch.stories.tsx
src/components/FormElements/ToggleSwitch/ToggleSwitch.tsx

Prevent immediate toggle func at ToggleSwitch by adding a `preventToggle` prop to it and a `toggle` func that can be used via imperative handle

chore: prevent immediate toggle func at ToggleSwitch

---

src/components/Table/Table.stories.tsx
src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
src/components/Table/components/Body.tsx
src/components/Table/components/DataCells.tsx
src/components/Table/components/Header.tsx
src/components/Table/components/TableRow.tsx
src/components/Table/helpers.ts
src/components/Table/styles.ts
src/components/Table/types.ts

[Task](https://app.asana.com/0/1202996243430204/1209871601806447/f)
In this PR:
- We make all table checkboxes available in the DOM for accessibility reasons (interaction).
- Fix undefined id values by defaulting table id to "table".
- Removed some cell keys that caused unnecessary cell re-rendering and de-focus of checkbox selections.
- Added the ability to specify a default accessor for labelledby checkbox reference.

chore(table): add checkbox in DOM order + various fixes

---

src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
src/components/FormElements/Select/styles.ts
src/components/FormElements/Select/types.ts

The menu of the modals is hidden behind the overlay. Thus, we need to increase z-index
---
- https://app.asana.com/0/0/1209821642847818

fix(select): increase z-index at selects with portaling enabled

---

src/components/FormElements/ToggleSwitch/ToggleSwitch.tsx
src/components/FormElements/ToggleSwitch/__tests__/__snapshots__/ToggleSwitch.test.tsx.snap
src/components/FormElements/ToggleSwitch/styles.ts

This pull request introduces a new `shouldOutline` property to the `ToggleSwitch` component, allowing developers to optionally add an outline to the toggle switch. The changes involve updates to the component's props, default values, and styles to support this new feature.

Add outline option for toggle switch

---

src/components/Table/Table.tsx
src/components/Table/reducer.ts

Recent changes introduced a hover bug. That means when hovering table rows, no actions are shown.

fix(table): fix hover issue

---

src/components/Dropdown/Dropdown.stories.tsx
src/components/Dropdown/Dropdown.test.tsx
src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
src/components/Dropdown/components/DropdownListItem.tsx
src/components/Dropdown/components/styles.ts
src/components/Dropdown/styles.ts
src/components/Dropdown/types.ts

This PR adds a divider element to the `Dropdown` component to improve the visual organization of options. This creates a clear visual separation between groups of items using consistent styling, making dropdowns easier to scan and navigate.
- Introduced a divider element rendered as a `div` with divider class and styles.
- Ensured disabled items remain unselectable.
- Updated component documentation and examples to demonstrate the divider usage.

chore(dropdown): add divider to organize list items
