epignosis/gnosis

- babel.config.json
- jest.config.js
- package-lock.json
- package.json
- rollup.config.js
Remove tree-shaking feature in order to integrate the design system in `create-react-app` apps.
> chore: remove tree-shaking

- .github/workflows/cd.yml
This PR adds a deployment workflow using Github Actions. 
> chore(ci): adds deploy configuration

- src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
- src/components/FormElements/Input/styles.ts
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Select/styles.ts
- src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
- src/components/FormElements/styles.ts
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
- src/components/Tabs/styles.ts
- src/theme/default/config/formElements.ts
**This PR resolves the following:**
1. Add border on Tabs header
2. Change the hover color on form elements ( Input, Textarea and Select)
> chore: component fixes

- src/components/Button/__snapshots__/Button.test.tsx.snap
- src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/Checkbox.test.tsx.snap
- src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/CheckboxGroup.test.tsx.snap
- src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
- src/components/FormElements/RadioGroup/RadioGroup.stories.tsx
- src/components/FormElements/RadioGroup/__tests__/__snapshots__/Radio.test.tsx.snap
- src/components/FormElements/RadioGroup/__tests__/__snapshots__/RadioGroup.test.tsx.snap
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
- src/components/FormElements/styles.ts
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap
- src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
- src/components/Tabs/styles.ts
- src/theme/default/colors.ts
- src/theme/default/config/button.ts
- src/theme/default/config/formElements.ts
- src/theme/default/config/loader.ts
- src/theme/default/config/modal.ts
- src/theme/default/config/pagination.ts
- src/theme/default/config/sidebar.ts
- src/theme/default/config/tabs.ts
- src/theme/default/defaultTheme.ts
This PR introduce some changes in theme colours
Renames blue colour to primary colour
Introduce primary accent colour
Replace some hardcoded colours
Radio group story change radios names 
BREAKING CHANGE: Tab item colour changed to be the same as the body colour
> feature: primary colour

- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.tsx
- src/theme/index.ts
Update Header, Body and Footers in order to accept HTML element props.
Also export the default theme.
> style(modal.tsx): update Header, Body and Footers in order to accept HTML element props

- src/icons/unit_complete.svg
- src/icons/unit_failed.svg
It was asked to update the failed and success icons
Updated the icons with the new ones.
> fix: completed failed icons

- src/components/ProgressBar/ProgressBar.test.tsx
- src/components/ProgressBar/ProgressBar.tsx
- src/components/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
Fix to show properly the percentage symbol in RTL languages
Add right-to-left mark in ProgressBar component
> fix: progress bar component in rtl

- src/components/FormElements/CheckboxGroup/Checkbox.stories.tsx
- src/components/FormElements/CheckboxGroup/Checkbox.tsx
- src/components/FormElements/RadioGroup/Radio.tsx
- src/components/FormElements/RadioGroup/RadioGroup.stories.tsx
Support JSX.Element on Checkbox and Radio components label
- Allow JSX.Element on Checkbox and Radio components label
- Create stories with these changes
> chore(checkbox.tsx, radio.tsx): make label on Checkbox and Radio accept JSX.Element

- src/components/Button/__snapshots__/Button.test.tsx.snap
- src/components/Button/styles.ts
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
On button component, replace focus with focus visible
> style(button.tsx): replace focus with focus-visible

- src/index.ts
This PR exports Table component types
> chore(table): export table types

- src/index.ts
> chore(table.tsx): export table types

- src/components/Table/Table.stories.tsx
- src/components/Table/components/Body.tsx
Remove check for actions on table body
> chore(table.tsx): remove check for actions on table body

- src/components/Modal/Modal.tsx
- src/components/Modal/styles.ts
Generally background in modals is changed .
We apply a dark overlay in modal background.
> all modals should have a dark overlay

- src/index.ts
ex. This PR export default theme alogn with it's type
> chore(theme): export default theme

- src/components/Table/Table.stories.tsx
The previous PR did not update the gnosis version. This is a dummy PR.
> fix: updating pagination gnosis version

- src/components/Pagination/Pagination.tsx
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/components/Pagination/styles.ts
UI changes that were missing in the last PR
- Hover color on buttons.
- Italics when opening the selection.
- Box shadow on list container.
> fix: styling changes in pagination

- src/components/Pagination/Pagination.tsx
on Pagination component, use a unique key for the li element
> fix(pagination.tsx): on Pagination component, use a unique key for the li element

- src/components/Pagination/Pagination.stories.tsx
- src/components/Pagination/Pagination.test.tsx
- src/components/Pagination/Pagination.tsx
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/components/Pagination/styles.ts
- src/components/Pagination/types.ts
This PR implements some fixes and improvements in Pagination component
- Change types naming to be more explanatory
- Use same template in stories
- Rtl styles
> fix(pagination): types and styles

- src/components/Chip/Chip.stories.tsx
- src/components/Chip/Chip.tsx
- src/components/Chip/__snapshots__/Chip.test.tsx.snap
- src/components/Chip/helpers.ts
- src/components/Chip/styles.ts
We noticed that chips might get really wide and it does not look good.
We implement a max width solution where the text appears as overflow and a tooltip appears at that moment.
> fix: overflow on chips

- src/components/FormElements/Input/Input.stories.tsx
- src/components/FormElements/Input/Input.tsx
- src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
- src/components/FormElements/Input/styles.ts
- src/components/FormElements/Label/Label.tsx
- src/components/FormElements/Label/styles.ts
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Select/styles.ts
- src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
- src/components/FormElements/styles.ts
- Added internal state to handle clear icon conditional rendering
- Added ref to handle focus issues
> fix: input changes

- src/components/FormElements/Input/Input.stories.tsx
- src/components/FormElements/Input/Input.tsx
- src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
- src/components/FormElements/Input/styles.ts
Fix Input component padding issues
> fix(input): fix input spacing issues

- src/theme/default/config/tabs.ts
> chore: redeploy

- src/components/Dropdown/Dropdown.tsx
> build(force redeploy): just for redeploy

- src/components/Dropdown/Dropdown.tsx
Description
Introduce dropdown component
Changes
Add dropdown component
> feat: dropdown

- src/components/Dropdown/Dropdown.tsx
> fix: redeploy

- src/index.ts
> chore: export dropdown

- src/index.ts
> chore: export dropdown types

- src/components/FormElements/Select/Select.tsx
> chore: deploy

- src/components/Dropdown/Dropdown.tsx
> fix: deploy

- src/components/FormElements/Select/Select.tsx
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Select/components/CustomMenuList.tsx
- src/components/FormElements/Select/data.ts
- src/components/FormElements/Select/styles.ts
Added improvement regarding styles.
— Improve styles of the scroll bar
— Improve spacing to match the dropdown spacing
— Multi-select, does not close when selecting an option
— Longer options do not wrap in the following line, a 3-dot suffix appears when word exceeds the width
— Add border-radius when hovering (only on select with inner search) — Select height now is correct (same as input)
> fix : Select component improvements

- src/components/FormElements/Select/Select.tsx
> feat: redeploy

- src/components/Button/__snapshots__/Button.test.tsx.snap
- src/components/Button/styles.ts
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/theme/default/config/button.ts
This PR implements some fixes in button component
- Fix primary button ghost and link colours
- Fix button loading state with noGutters props enabled
---
- https://app.asana.com/0/0/1205430381361066
> fix: primary button colours

- src/components/FormElements/Select/Select.tsx
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/theme/default/config/formElements.ts
Add color and background when navigating through options with keyboard
> style(select.tsx): add color and background when navigating through options with keyboard

- src/components/FormElements/Select/Select.tsx
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
change the focused color on select
> style(Select.tsx): change the focused color on select

- src/components/Button/__snapshots__/Button.test.tsx.snap
- src/components/Button/styles.ts
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/theme/default/config/button.ts
Add a new prop on color object "hoverColor" and update colors for ghost buttons danger and success based on design system
**Danger button(ghost variant):**
- background color from colors.red.lightest to colors.red.light
- Introduced a new prop "hoverColor" that represents the text color of the button on hover
**Success button(ghost variant):**
- background color from colors.green.lightest to colors.green.light
- Introduced a new prop "hoverColor" that represents the text color of the button on hover
> style(button.tsx): update ghost buttons danger and success

- src/components/Tooltip/Tooltip.tsx
Interactive tooltip prop produced an error in TLMS+
Adding an appendTo prop to document.body
> fix: interactive tooltip fix

- src/components/Result/Result.stories.tsx
- src/components/Result/Result.tsx
- src/components/Result/__snapshots__/Result.test.tsx.snap
- src/components/Result/styles.ts
- src/theme/default/config/result.ts
This PR implements the ability to add border to Result component
Adds the `hasBorder` property to Result component
> fix(result): add border to Result component

- src/components/Table/Table.stories.tsx
- src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
- src/components/Table/components/Body.tsx
- src/components/Table/components/Header.tsx
- src/components/Table/styles.ts
- src/components/Table/types.ts
Add autohide row selection in table.
> feat(table component): add autohide row selection

- src/components/FormElements/CheckboxGroup/Checkbox.stories.tsx
- src/components/FormElements/CheckboxGroup/Checkbox.tsx
- src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/Checkbox.test.tsx.snap
- src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/CheckboxGroup.test.tsx.snap
- src/components/FormElements/CheckboxGroup/styles.ts
- src/components/FormElements/Input/Input.stories.tsx
- src/components/FormElements/Input/Input.tsx
- src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
- src/components/FormElements/Input/styles.ts
- src/components/FormElements/Select/Select.stories.tsx
- src/components/FormElements/Select/Select.tsx
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Select/styles.ts
- src/components/FormElements/Select/types.ts
- src/components/FormElements/Textarea/Textarea.stories.tsx
- src/components/FormElements/Textarea/Textarea.tsx
- src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
- src/components/FormElements/Textarea/styles.ts
- src/theme/default/config/formElements.ts
Implementation of required prop in some form field elements in order to show an asterisk next to the field label.
> feat(form fields): add required prop (mandatory)

- src/components/Pagination/Pagination.tsx
- src/components/Pagination/components/PaginationSelector.tsx
Fix pagination styling when there is only one page to show.
> fix(pagination): fix pagination styling when there is only one page

- src/components/Pagination/components/PaginationSelector.tsx
Prevent pages dropdown click on single pages.
> fix(pagination): prevent dropdown pages on single page

- src/components/Pagination/components/PaginationSelector.tsx
> fix(pagination): minor fix on page button

- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Select/styles.ts
Minor update in select component
> fix: minor fix in select styles

- src/components/Tag/__snapshots__/Tag.test.tsx.snap
- src/components/Tag/styles.ts
- src/theme/default/config/tag.ts
ex. This PR implements some fixes in Tag component styles and theme
- Fix font size, height, padding, border-radius
- Fix default colour and background colour
> fix(tag): styles and theme fixes

- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Select/components/CustomMenuList.tsx
> fix(select): remove text container

- src/components/Dropdown/Dropdown.tsx
- src/components/FormElements/Input/Input.stories.tsx
- src/components/FormElements/Input/Input.tsx
- src/components/FormElements/Input/SearchInput.tsx
- src/components/FormElements/Select/components/CustomMenuList.tsx
[Task](https://app.asana.com/0/1202297387514885/1205546482343450/f)
> chore(set autofocus option): set autofocus option for searchable select & dropdown

- src/components/FormElements/Select/styles.ts
Task: [URL](https://app.asana.com/0/1202297387514885/1205680492796534/f)
> fix(fix disabled select pointers): fix cursor pointers in disabled select fields

- src/components/Button/__snapshots__/Button.test.tsx.snap
- src/components/Button/styles.ts
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
This PR implements a fix for buttons with icons
Fixes styles for buttons with icon before and icon after that have the noGutters property
> fix(button): noGutters styles for buttons with icons

- src/components/Card/Body.tsx
- src/components/Card/__snapshots__/Card.test.tsx.snap
Add className on Body.tsx on Card component
> refactor(body.tsx): add className on Body.tsx on Card component

- src/components/Tabs/styles.ts
keep the border of tabs in all sizes.
> style(tabs component): keep border bottom in all sizes in tabs component

- src/components/Dropdown/Dropdown.test.tsx
- src/components/Dropdown/Dropdown.tsx
This PR implements a fix for Dropdown component list
Opening the dropdown component scrolls to the list wrapper bottom
> fix(dropdown): scroll to list bottom on open

- src/components/Pagination/Pagination.stories.tsx
- src/components/Pagination/Pagination.test.tsx
- src/components/Pagination/Pagination.tsx
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/components/Pagination/types.ts
> fix(pagination): add missing translation

- src/components/Dropdown/Dropdown.tsx
ex. This PR reverts overflow logic on Dropdown component
> chore: revert overflow logic

- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/types.ts
Add emptyStateText prop for the empty state text
> refactor(dropdown.tsx): add emptyStateText prop

- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/types.ts
Add placeholderText prop for Dropdown search input
> refactor(dropdown.tsx): Add placeholderText prop for Dropdown search input

- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/Table/components/Header.tsx
- src/components/Table/types.ts
> fix(tables): fix issue with sorting in tables

- src/components/Table/components/Header.tsx
> fix(table): various fixes

- src/components/Table/components/Header.tsx
> fix(table): fix

- src/components/Table/components/Header.tsx
> fix(table): small fix

- src/components/Table/styles.ts
> fix(tables): very minor fix on th hover

- src/components/Alert/Alert.stories.tsx
> chore(alert): disable alert component from storybook but still export it

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/helpers.tsx
- src/components/Dropdown/types.ts
This PR implements fix placement feature for Dropdown component
Applying fix in dropdown placement when there is no space available based on the provided placement
> feat(dropdown): fix placement

- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/Dropdown/styles.ts
- src/components/Dropdown/types.ts
This PR implements some fixes on Dropdown component placement
- Issues with fixed placement in some placement options
- Styling fixes in some placement options
> fix(dropdown): fix placement issues

- src/components/Pagination/Pagination.tsx
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/components/Pagination/components/PaginationSelector.tsx
- src/components/Pagination/components/styles.ts
- src/components/Pagination/types.ts
Add listPlacement property for the posistion of the ul list
The default prop is "top", but can change to "bottom"
> fix(paginationSelector.tsx): Add listPlacement prop

- src/components/Pagination/Pagination.tsx
Add listPlacement to page size selector
> fix(pagination.tsx): Add listPlacement to page size selector

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/types.ts
Return if list open on dropdown
> style(return if list open on dropdown): return if list open on dropdown

- src/components/FormElements/Input/helpers.ts
This PR implements a fix on allowed keyboard buttons on number input
Added the ArrowUp and ArrowDown keys on the allowed keys list
> fix(input): allow arrow up and arrow down keys in number input

- src/components/FormElements/CheckboxGroup/Checkbox.tsx
- src/components/FormElements/RadioGroup/Radio.tsx
- src/components/FormElements/RadioGroup/__tests__/__snapshots__/Radio.test.tsx.snap
- src/components/FormElements/RadioGroup/__tests__/__snapshots__/RadioGroup.test.tsx.snap
- src/components/FormElements/RadioGroup/styles.ts
- Radio component styles for vey long text
- Apply readOnly property in Radio and Checkbox components
---
- https://app.asana.com/0/0/1206178586821619
> fix(radio, checkbox): fix styles and readonly property

- src/components/FormElements/Select/Select.tsx
- src/components/FormElements/Select/data.ts
If Select component has more than 10 options then we show inner search
---
- https://app.asana.com/0/0/1206110601796558
> refactor: select has search if options > 10

- src/components/FormElements/Select/Select.tsx
> fix: fix default inner search for select when having grouped options

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/Dropdown/styles.ts
- src/components/Dropdown/types.ts
- src/theme/default/config/dropdown.ts
This PR implements the disabled state of a dropdown item.
You can now pass isDisabled prop in the dropdown list item.
> feat(dropdown): add disabled state

- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/Table/types.ts
> feat: extend table to support resetting rows

- src/components/Table/Table.stories.tsx
- src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
- src/components/Table/components/Cell.tsx
- src/components/Table/styles.ts
This PR implements a fix on Table selection checkboxes when auto hide is enabled
> fix: table auto hide styles

- src/components/Table/Table.tsx
Reset selected rows when unmounting the table
> fix(table): reset selected rows when unmounting

- src/components/FormElements/Select/Select.tsx
Better handle how menu is closing.
> fix(select): improve indicator

- src/components/Table/Table.tsx
Reverting those [changes](https://github.com/epignosis/gnosis/pull/282)
> fix(table): revert latest change

- src/components/FormElements/Select/components/CustomMenuList.tsx
> fix(select): handle menu open

- src/components/FormElements/Select/Select.tsx
> fix(deploy): for deploy

- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/Table/components/Body.tsx
- src/components/Table/components/Cell.tsx
- src/components/Table/components/Header.tsx
- src/components/Table/components/TableRow.tsx
- src/components/Table/constants.ts
- src/components/Table/reducer.ts
- src/components/Table/types.ts
Creating a separate TableRow component to possibly decrease the number of renders.
> perf(table): create separate tableRow component

- src/components/Table/Table.stories.tsx
- src/components/Table/components/Cell.tsx
- src/components/Table/components/TableRow.tsx
This PR implements fixes row selection triggering also row select
> fix(table): row click triggered from row selection

- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
- src/components/Table/components/DataCells.tsx
- src/components/Table/components/Header.tsx
- src/components/Table/components/TableRow.tsx
- src/components/Table/types.ts
- src/index.ts
Improve table performance by extracting accessors into separate component.
> perf(table): more changes to improve perfomance

- src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
- src/components/Table/components/DataCells.tsx
> fix(datacell): remove extra char

- src/components/ProgressBar/ProgressBar.stories.tsx
- src/components/ProgressBar/ProgressBar.tsx
- src/components/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
- src/components/ProgressBar/styles.ts
- src/theme/default/config/progressBar.ts
This PR implements the addition of label and color properties in ProgressBar component
> feat(progressbar): add label and color properties

- src/components/FormElements/Input/Input.tsx
- src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
- src/components/FormElements/Select/Select.test.tsx
- src/components/FormElements/Select/Select.tsx
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/helpers/index.ts
In this PR I added some missing data-testids.
> refactor(input and select): added data-testids

- src/components/Table/Table.tsx
- src/components/Table/constants.ts
- src/components/Table/reducer.ts
- src/components/Table/types.ts
Add a new imperative handler to reset selected rows.
> feat(table): new imperative handler to reset selected rows

- src/components/Table/types.ts
> fix(table): missing type

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/types.ts
- src/theme/default/config/button.ts
This PR introduces primaryDarker colour for Button component
Allow to pass html div attributes to dropdown props
> chore(button): button primary darker colour

- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/Tabs.test.tsx
- src/components/Tabs/Tabs.tsx
- src/components/Tabs/TabsNavItem.tsx
- src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
In this PR I added data-testids to tabs.
> refactor(tabs): added data-testids

- src/components/Table/Table.tsx
- src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
- src/components/Table/components/Header.tsx
In this PR I added data-testids to Table including column header and sorting arrow.
> refactor(table): added data-testids

- src/components/Loaders/Loader.stories.tsx
- src/components/Loaders/Loader.tsx
This PR implements `clip` type of Loader component
Fixes primary lighter Button border colour
> feat(loader): implement clip loader

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
This PR adjusts menu position when there is not available space
> feat(dropdown): adjust menu position when there is not available space

- src/components/Pagination/Pagination.tsx
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
https://app.asana.com/0/1202996243430204/1206693961112324/f
> chore(pagination): add some missing test ids

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/components/Button/styles.ts
> chore(Button.tsx): add small button size

- src/components/FormElements/Select/Select.tsx
> chore(deploy only): to redeploy

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/components/Button/__snapshots__/Button.test.tsx.snap
- src/components/Button/styles.ts
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/theme/default/config/button.ts
This PR implements changes on `Button` component
- Updates the primary light `Button` theme
- Introduces `underlined` property
> chore(primary light button): update primary light theme colours

- src/components/Pagination/Pagination.stories.tsx
- src/components/Pagination/Pagination.test.tsx
- src/components/Pagination/Pagination.tsx
- src/components/Pagination/components/PaginationSelector.tsx
- src/components/Pagination/types.ts
This PR implements the disable state of `Pagination` component
> feat(pagination): implement pagination disable state

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.test.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/types.ts
- src/components/FormElements/Input/Input.stories.tsx
- src/components/FormElements/Input/SearchInput.tsx
This PR implements the disable state of `Dropdown` and `SearchInput` component
> Feat: Add dropdown and search input disable state

- package.json
> chore(dropdown): we need to re-trigger release

- src/components/Dropdown/Dropdown.tsx
This PR is related to https://app.asana.com/0/0/1206949514296771/f
> chore(dropdown): add testid to the clickable items

- .github/workflows/deploy_staging.yml
- .github/workflows/release_staging.yml
This PR implements the Github Action for deploying to development environment.
---
- https://app.asana.com/0/0/1206876878503453
> add development release workflow

- src/components/FormElements/CheckboxGroup/Checkbox.tsx
- src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/Checkbox.test.tsx.snap
- src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/CheckboxGroup.test.tsx.snap
- src/components/FormElements/Textarea/Textarea.tsx
- src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
Add data-testids in checkbox and tetxtarea label
> chore: add data-testids in checkbox and tetxtarea label

- src/components/FormElements/ToggleSwitch/ToggleSwitch.stories.tsx
- src/components/FormElements/ToggleSwitch/ToggleSwitch.tsx
- src/components/FormElements/ToggleSwitch/__tests__/ToggleSwitch.test.tsx
- src/components/FormElements/ToggleSwitch/__tests__/__snapshots__/ToggleSwitch.test.tsx.snap
- src/components/FormElements/ToggleSwitch/styles.ts
- src/index.ts
- src/theme/default/config/formElements.ts
https://app.asana.com/0/1202996243430204/1204768265432316/f
> feat(add toggle switch): add new toggle switch component

- src/components/FormElements/Select/Select.tsx
- src/components/FormElements/Select/types.ts
This PR adds the count needed for the inner search to appear in select as a prop.
> feat(select): add count options for inner search as prop

- src/components/Card/Card.stories.tsx
- src/components/Card/Card.test.tsx
- src/components/Card/Card.tsx
This PR adds the ability to manually manipulate `Card.Hover`
> feat(card): ability to manipulate card hover

- src/components/FormElements/ToggleSwitch/ToggleSwitch.stories.tsx
- src/components/FormElements/ToggleSwitch/ToggleSwitch.tsx
- src/components/FormElements/ToggleSwitch/__tests__/__snapshots__/ToggleSwitch.test.tsx.snap
- src/components/FormElements/ToggleSwitch/styles.ts
- src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
- src/components/Tabs/styles.ts
Medium size toggle to accept icon.
> fix(toggle switch): accept internal icon and size fix

- src/components/Table/components/TableRow.tsx
Check if this will fix the hover row bug
> fix(table): use onMouseMove to potentially fix hover bug

- src/components/Table/components/TableRow.tsx
> fix(table): onMouseEnter

- src/icons/index.ts
- src/icons/legacy/radio-selected-filled.svg
> chore(icons.tsx): add radio selected filled svg

- src/icons/legacy/radio-selected-filled.svg
Radio icon filled stroke color
> chore(icons.tsx): radio icon filled stroke color

- src/icons/index.ts
- src/icons/legacy/unit-pending-filled.svg
> chore(icons.tsx): add unit pending filled svg

- src/index.ts
- src/theme/utils/typography.ts
The purpose of this PR is to eliminate duplicate code in tlms+ ([see file](https://github.com/epignosis/etp-client-web/blob/master/src/styles/typography.ts))
---
- https://app.asana.com/0/0/1207784545377212
> chore(typography): export typescales

- src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
- src/components/Table/components/DataCells.tsx
This PR adds data testids for table row cells
> feat: add data-testids for table row cells

- src/components/Result/Result.tsx
- src/components/Result/__snapshots__/Result.test.tsx.snap
This PR adds data-testids to Result body component
> Chore: add data-testids to Result body component

- src/components/FormElements/Select/Select.stories.tsx
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Select/components/CustomMenuList.tsx
- src/components/FormElements/Select/styles.ts
- src/components/FormElements/Select/types.ts
> feat(select): improvements

- src/components/Table/components/Header.tsx
> fix(table): pass unique id to avoid bug

- src/components/Table/components/Body.tsx
- src/components/Table/components/TableRow.tsx
Add unique ids to checkbox at table rows
> fix(checkbox): add unique id's

- src/components/Tooltip/Tooltip.tsx
[Task](https://app.asana.com/0/1202996243430204/1208141190680702/f)
> chore(tooltip): added a new parentRole prop for accessibility

- src/components/FormElements/Select/Select.stories.tsx
- src/components/FormElements/Select/Select.tsx
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Select/components/CustomOption.tsx
- src/components/FormElements/Select/data.ts
- src/components/FormElements/Select/styles.ts
- src/components/FormElements/Select/types.ts
This PR introduces `menuMaxWidth` property and tooltip on menu options
> feat: select option tooltip

- src/components/Drawer/Drawer.tsx
- src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
Change the div container of the drawer to dialog.
> chore(drawer): remove aria roles that are not allowed in drawer

- src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
- src/components/FormElements/Label/__snapshots__/Label.test.tsx.snap
- src/components/FormElements/Label/styles.ts
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
[URL](https://app.asana.com/0/1207921943967270/1208199504324576/f)
> Long Custom User Fields Cut Off on Signup Screen

- src/components/FormElements/Select/components/CustomMenuList.tsx
- src/components/FormElements/Select/types.ts
> chore(select): minor type change

- src/components/FormElements/Select/Select.tsx
- src/components/FormElements/Select/components/CustomMultiValueLabel.tsx
- src/components/FormElements/Select/components/CustomSingleValue.tsx
- src/components/FormElements/Select/styles.ts
This PR implements a tooltip on `Select` component selected values
This PR adds custom `SingleValue` and `MultiValueLabel` components to show tooltip when the selected value is cut
---
- https://app.asana.com/0/0/1208209005185125
> feat(select): apply tooltip on selected values

- src/components/FormElements/Select/Select.stories.tsx
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Select/components/CustomMenuList.tsx
- src/components/FormElements/Select/styles.ts
- src/components/FormElements/Select/types.ts
> chore(select): turn string into jsx

- src/components/FormElements/Select/components/CustomMultiValueLabel.tsx
- src/components/FormElements/Select/components/CustomOption.tsx
- src/components/FormElements/Select/components/CustomSingleValue.tsx
Memoize Select components with tooltip
> fix(select): memoization in component with tooltip

- src/components/Card/Card.stories.tsx
> chore(trigger release): trigger release action

- src/components/FormElements/Select/Select.tsx
> fix: mistake on release

- src/components/FormElements/Select/helpers.tsx
> chore(redeploy): redeploy

- src/components/FormElements/Select/Select.stories.tsx
- src/components/FormElements/Select/Select.tsx
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Select/helpers.tsx
- src/components/FormElements/Select/styles.ts
- src/components/FormElements/Select/types.ts
Prop update on select component
> feat(select): props change

- src/icons/index.ts
> chore(icons): export icon from index

- src/components/FormElements/ToggleSwitch/ToggleSwitch.stories.tsx
- src/components/FormElements/ToggleSwitch/__tests__/__snapshots__/ToggleSwitch.test.tsx.snap
- src/components/FormElements/ToggleSwitch/styles.ts
- src/theme/default/config/formElements.ts
- Added a missing story with the description test
- Replaced the description color
> fix(a11y toggle description color): description color changes

- src/components/Result/Result.tsx
- src/components/Result/__snapshots__/Result.test.tsx.snap
- src/components/Result/styles.ts
- src/theme/default/config/result.ts
Allow for heading level options.
> chore(result): add a heading level option

- src/components/Card/Drawer.tsx
- src/components/Card/__snapshots__/Card.test.tsx.snap
> feat: upgrade react version

- package-lock.json
- package.json
- src/components/Alert/Alert.stories.tsx
- src/components/MediaPlayer/AudioPlayer/AudioPlayer.tsx
- src/components/MediaPlayer/MediaPlayer.tsx
- src/components/MediaPlayer/VideoPlayer/VideoPlayer.tsx
- src/components/MediaPlayer/VideoPlayer/types.ts
Remove lazy import that leads to breaking the video player
> feat(videoplayer): remove lazy import

- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/Tabs.tsx
- src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
- src/components/Tabs/styles.ts
ex. This PR adds functionality of adding an inline-end component to Tabs.tsx nav bar. 
The need arised from having to implement the ["How the course store works"](https://www.figma.com/design/qq1f8hMl8zsLFoJLYFnPIi/Admin?node-id=17117-6799&m=dev) button
> feat(tabs.tsx): added inline end component functionality

- src/components/StatusTag/StatusTag.stories.tsx
- src/components/StatusTag/StatusTag.test.tsx
- src/components/StatusTag/StatusTag.tsx
- src/components/StatusTag/styles.ts
- src/index.ts
- src/theme/default/config/index.ts
- src/theme/default/config/statusTag.ts
- src/theme/default/defaultTheme.ts
[Design Spec task](https://app.asana.com/0/1204116037405608/1208386416231993/f)
Introducing a new status tag component.
> feat(statustag): introduced a new status tag component

- src/theme/default/config/statusTag.ts
Changed the red base color to red dark for A11Y reasons.
> chore(status tag): change red base to dark red for A11y puproses

- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Select/components/CustomMultiValueLabel.tsx
- src/components/FormElements/Select/components/CustomOptionComponent.tsx
- src/components/FormElements/Select/components/CustomSingleValue.tsx
Improve a11y on select's tooltips.
---
- https://app.asana.com/0/0/1208202314774857
> chore(select): a11y on tooltips

- src/components/StatusTag/StatusTag.tsx
- src/components/StatusTag/styles.ts
- src/index.ts
Export status tag color types.
> chore(status tag): export status tag color types

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Re-structured the JSX in order to be semantic and A11Y compatible.
> chore(dropdown): re-structured the JSX for A11Y support.

- src/components/Breadcrumbs/Breadcrumbs.stories.tsx
- src/components/Breadcrumbs/Breadcrumbs.test.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/components/Breadcrumbs/styles.ts
- src/index.ts
- src/theme/default/config/breadcrumbs.ts
- src/theme/default/config/index.ts
- src/theme/default/defaultTheme.ts
[Design specs](https://app.asana.com/0/1204116037405608/1206599594779505/f)
[Figma Design](https://www.figma.com/design/1aeuMSG5ehrDd45ABt4HCr/TLMS%2B-Design-System?node-id=13654-3336&node-type=canvas&m=dev)
[Task URL](https://app.asana.com/0/1204116037405608/1208379057043842/f)
Introducing the new breadcrumbs implementation.
> feat(breadcrumbs): add new breadcrumbs implementation

- src/components/FormElements/Input/Input.stories.tsx
- src/components/FormElements/Input/Input.tsx
- src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
- src/components/FormElements/Input/styles.ts
We need to implement hide/show password. Icon after should be clickable.
> feat(input): add onIconClick 

- src/components/Card/Card.stories.tsx
- src/components/Card/Card.tsx
- src/components/Card/__snapshots__/Card.test.tsx.snap
- src/components/Card/styles.ts
- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/Dropdown/styles.ts
- src/theme/default/config/card.ts
Add hasShadow and hasBorder props, and change the hover bg color
> chore(card.tsx): Add hasShadow and hasBorder props, and change the hover bg color

- src/components/Breadcrumbs/Breadcrumbs.stories.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/components/Breadcrumbs/styles.ts
- src/theme/default/config/breadcrumbs.ts
> chore(breadcrumbs): design tweaks

- src/components/StatusTag/StatusTag.tsx
Added an onClick attribute at StatusTag component
> chore: add onclick at StatusTag

- src/components/FormElements/Select/data.ts
This PR add a hint capability to Select's option
> feat(select): add hint capability for select option

- src/components/FormElements/Select/Select.stories.tsx
- src/components/FormElements/Select/components/CustomOptionComponent.tsx
- src/components/FormElements/Select/helpers.tsx
- src/components/FormElements/ToggleSwitch/ToggleSwitch.tsx
> fix(select.tsx): fix select nested options

- src/components/Card/Card.tsx
- src/components/Card/__snapshots__/Card.test.tsx.snap
- src/components/Card/styles.ts
[Task](https://app.asana.com/0/1202996243430204/1206359765169573/f)
> chore(cards): remove shadows from cards

- src/theme/utils/global.ts
Add underline text decoration in anchor tag elements
> chore(anchor element): underline anchor tag

- src/components/Tabs/Tabs.tsx
- src/components/Tabs/TabsNavItem.tsx
[Task](https://app.asana.com/0/1204116037405608/1208179119637538/f)
> chore(tabs): make tabs navigatable with keyboard

- src/components/Tabs/Tabs.tsx
- src/components/Tabs/TabsNavItem.tsx
- src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
- src/components/Tabs/styles.ts
I fixed a case where a user is able to navigate to tabs that are undefined, we don't want to navigate to undefined tabs.
> chore(tabs): fix issue with invisible tab

- src/components/Tabs/Tabs.tsx
> chore(tabs): whatever

- src/components/Table/Table.tsx
- src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
This PR is related to this [TASK](https://app.asana.com/0/1202996243430204/1208786274399142/f)
In this PR, I updated the table component to ensure sorting reflects changes in external props.
> fix(table): fix inability to update sorting props externally

- src/components/Modal/Modal.test.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/__snapshots__/Modal.test.tsx.snap
- src/components/Modal/styles.ts
> feat(modal): add modal sizes

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/components/Button/constants.ts
- src/theme/default/config/button.ts
This PR adds the `white` color option in `Button` component
> feat(button): implement white color button

- src/components/Dropdown/Dropdown.tsx
This PR adds stopPropagation on toggle click event
> chore(dropdown): stop propagation on toggle element click

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/index.ts
- src/theme/default/config/button.ts
Add orange button color and export Color type from Button.tsx
> chore(button.tsx): add orange button color

- src/components/Heading/Heading.tsx
Allow Heading component to accept ref
> chore(heading.tsx): make heading component accept ref

- src/components/Pagination/Pagination.stories.tsx
- src/components/Pagination/Pagination.test.tsx
- src/components/Pagination/Pagination.tsx
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/components/Pagination/components/PaginationSelector.tsx
- src/components/Pagination/types.ts
Add a11yTranslations object and aria labels
> chore(pagination.tsx): add a11yTranslations object and aria labels

- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Added the ability to focus and toggle the dropdown via keyboard.
> chore(dropdown): add keyboard accessibility for toggling dropdown

- src/icons/index.ts
- src/icons/logos/index.ts
- src/icons/logos/lti.svg
> chore(icons.tsx): add LTI icon

- src/components/StatusTag/StatusTag.stories.tsx
- src/components/StatusTag/StatusTag.tsx
This PR adds `ariaLabel` prop to `StatusTag` component
> chore: status tag aria label

- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/Dropdown/components/DropdownListItem.tsx
- src/components/Dropdown/components/DropdownListItemTitle.tsx
- src/components/Dropdown/components/styles.ts
- src/components/Dropdown/helpers.tsx
- src/components/Dropdown/styles.ts
- src/components/FormElements/Input/SearchInput.tsx
This PR refactors Dropdown component
- This PR introduces `DropdownListItem` and `DropdownListItemTitle` component for better code separation
- This PR fixes propagation on DropdownListItem `click` and `keydown` events
---
- https://app.asana.com/0/0/1209521496944570
> refactor(dropdown): create list item and list item title components

- src/components/FormElements/ToggleSwitch/ToggleSwitch.tsx
- src/components/FormElements/ToggleSwitch/__tests__/ToggleSwitch.test.tsx
- src/components/FormElements/ToggleSwitch/__tests__/__snapshots__/ToggleSwitch.test.tsx.snap
[Task](https://app.asana.com/0/1207933003201203/1209639306201622)
> chore(toggleswitch): add new prop labelledById to replace the id in aria-label

- src/components/Modal/__snapshots__/Modal.test.tsx.snap
- src/components/Modal/styles.ts
fix Modal header button broken styles
> chore(modal.tsx): fix button broken styles

- src/components/Tabs/Tabs.tsx
[Task](https://app.asana.com/0/1207933003201203/1209520697673682/f)
> chore(tabs): add test IDs for navigation and content elements

- src/components/Alert/Alert.test.tsx
> chore: minor change to bump version

- src/components/Button/Button.tsx
- src/components/Button/__snapshots__/Button.test.tsx.snap
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
Add classname to gnosis buttons
> feat(button): add class to distinguish gnosis button

- src/components/FormElements/Textarea/Textarea.stories.tsx
- src/components/FormElements/Textarea/Textarea.tsx
- src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
- src/components/FormElements/Textarea/styles.ts
This PR implements adds `rows` prop to Textarea component
> fix(textarea): add rows prop to Textarea component

- src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
- src/components/Drawer/components/Header.tsx
- src/components/Drawer/components/styles.ts
- src/theme/default/config/drawer.ts
This PR replaces the Drawer 's custom close button with a Gnosis button
> fix(drawer): replace custom close button with Gnosis button

- src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
- src/components/Button/__snapshots__/Button.test.tsx.snap
- src/components/Chip/__snapshots__/Chip.test.tsx.snap
- src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/Checkbox.test.tsx.snap
- src/components/FormElements/CheckboxGroup/__tests__/__snapshots__/CheckboxGroup.test.tsx.snap
- src/components/FormElements/Input/__snapshots__/Input.test.tsx.snap
- src/components/FormElements/Label/__snapshots__/Label.test.tsx.snap
- src/components/FormElements/RadioButtonGroup/__tests__/__snapshots__/RadioButton.test.tsx.snap
- src/components/FormElements/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup.test.tsx.snap
- src/components/FormElements/RadioGroup/__tests__/__snapshots__/Radio.test.tsx.snap
- src/components/FormElements/RadioGroup/__tests__/__snapshots__/RadioGroup.test.tsx.snap
- src/components/FormElements/Select/__snapshots__/Select.test.tsx.snap
- src/components/FormElements/Textarea/__snapshots__/Textarea.test.tsx.snap
- src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- src/components/Result/__snapshots__/Result.test.tsx.snap
- src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap
- src/components/Tag/__snapshots__/Tag.test.tsx.snap
- src/theme/default/TypographyDocs.stories.tsx
- src/theme/utils/typography.ts
Change type scale sizes to produce rounded values in pixels
BREAKING CHANGE: This change will change the font size of the Text component and all other texts using the typeScale font sizes
> feat(typography): change type scale sizes

- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/Table/components/Header.tsx
- src/components/Table/components/TableRow.tsx
- src/components/Table/types.ts
Add table support for row persistence
> feat(table): add support for row persistence

- src/components/Tooltip/Tooltip.tsx
> chore: prevent tooltip to open on a single tap on touch devices
